// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZgjedhjetApi.Data;

#nullable disable

namespace ZgjedhjetApi.Migrations
{
    [DbContext(typeof(LifeDbContext))]
    partial class LifeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZgjedhjetApi.Models.Entities.Zgjedhjet", b =>
                {
                    b.Property<string>("Kategoria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Komuna")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Qendra_e_votimit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Vendvotimi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Partia111")
                        .HasColumnType("int");

                    b.Property<int>("Partia112")
                        .HasColumnType("int");

                    b.Property<int>("Partia113")
                        .HasColumnType("int");

                    b.Property<int>("Partia114")
                        .HasColumnType("int");

                    b.Property<int>("Partia115")
                        .HasColumnType("int");

                    b.Property<int>("Partia116")
                        .HasColumnType("int");

                    b.Property<int>("Partia117")
                        .HasColumnType("int");

                    b.Property<int>("Partia118")
                        .HasColumnType("int");

                    b.Property<int>("Partia119")
                        .HasColumnType("int");

                    b.Property<int>("Partia120")
                        .HasColumnType("int");

                    b.Property<int>("Partia121")
                        .HasColumnType("int");

                    b.Property<int>("Partia122")
                        .HasColumnType("int");

                    b.Property<int>("Partia123")
                        .HasColumnType("int");

                    b.Property<int>("Partia124")
                        .HasColumnType("int");

                    b.Property<int>("Partia125")
                        .HasColumnType("int");

                    b.Property<int>("Partia126")
                        .HasColumnType("int");

                    b.Property<int>("Partia127")
                        .HasColumnType("int");

                    b.Property<int>("Partia128")
                        .HasColumnType("int");

                    b.Property<int>("Partia129")
                        .HasColumnType("int");

                    b.Property<int>("Partia130")
                        .HasColumnType("int");

                    b.Property<int>("Partia131")
                        .HasColumnType("int");

                    b.Property<int>("Partia132")
                        .HasColumnType("int");

                    b.Property<int>("Partia133")
                        .HasColumnType("int");

                    b.Property<int>("Partia134")
                        .HasColumnType("int");

                    b.Property<int>("Partia135")
                        .HasColumnType("int");

                    b.Property<int>("Partia136")
                        .HasColumnType("int");

                    b.Property<int>("Partia137")
                        .HasColumnType("int");

                    b.Property<int>("Partia138")
                        .HasColumnType("int");

                    b.HasKey("Kategoria", "Komuna", "Qendra_e_votimit", "Vendvotimi");

                    b.ToTable("Zgjedhjet", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
